# Generated by Django 3.1.7 on 2021-03-16 17:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventsLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('event', models.CharField(max_length=100)),
                ('meta_data', jsonfield.fields.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_event_logs',
            },
        ),
        migrations.CreateModel(
            name='WebhookLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('method', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'webhook_links',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
